// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHNPrWrOVLdSl-8GiYYfFtG3wX6b1e0s',
    appId: '1:641047221546:web:e9f478d65b81272fdeba53',
    messagingSenderId: '641047221546',
    projectId: 'todolist-d0234',
    authDomain: 'todolist-d0234.firebaseapp.com',
    storageBucket: 'todolist-d0234.appspot.com',
    measurementId: 'G-HE89DBPVYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7re_MaIRFt21vPJh4OUmGXV02hfS_t4',
    appId: '1:641047221546:android:14033337f420f2c2deba53',
    messagingSenderId: '641047221546',
    projectId: 'todolist-d0234',
    storageBucket: 'todolist-d0234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMZ9n6Ml81MNzGpfqKx7-eSFNGT3IqWE',
    appId: '1:641047221546:ios:573ca1204bb75b6fdeba53',
    messagingSenderId: '641047221546',
    projectId: 'todolist-d0234',
    storageBucket: 'todolist-d0234.appspot.com',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKMZ9n6Ml81MNzGpfqKx7-eSFNGT3IqWE',
    appId: '1:641047221546:ios:573ca1204bb75b6fdeba53',
    messagingSenderId: '641047221546',
    projectId: 'todolist-d0234',
    storageBucket: 'todolist-d0234.appspot.com',
    iosBundleId: 'com.example.todolistapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtHNPrWrOVLdSl-8GiYYfFtG3wX6b1e0s',
    appId: '1:641047221546:web:69649fa80f07e3a8deba53',
    messagingSenderId: '641047221546',
    projectId: 'todolist-d0234',
    authDomain: 'todolist-d0234.firebaseapp.com',
    storageBucket: 'todolist-d0234.appspot.com',
    measurementId: 'G-9B0RCNHG4W',
  );
}
